version: '3.2'

services:

    create_certs:
        container_name: create_certs
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
        command: >
            bash -c '
            if [[ ! -f /certs/bundle.zip ]]; then
                bin/elasticsearch-certutil cert --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
                unzip /certs/bundle.zip -d /certs; 
            fi;
            '
        working_dir: /usr/share/elasticsearch
        volumes: ['./certs:/certs', './instances:/usr/share/elasticsearch/config/certificates']
